AWSTemplateFormatVersion: 2010-09-09
Description: >
  Resources for creating a virtual private cloud (VPC).

################################################################################
Parameters:
################################################################################

  CidrBlock:
    Type: String
    Description: The Classless Inter-Domain Routing block to use for the VPC.
    Default: 10.0.0.0/16

################################################################################
Outputs:
################################################################################

  VpcId:
    Value: !Ref Vpc
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"

  CidrBlock:
    Value: !Ref CidrBlock
    Export:
      Name: !Sub "${AWS::StackName}-CidrBlock"

################################################################################
Resources:
################################################################################

  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref CidrBlock
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-VPC"
